<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="4" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Test_Automation_AutomationSuite" duration-ms="1519" started-at="2018-11-22T02:47:47Z" finished-at="2018-11-22T02:47:48Z">
    <groups>
      <group name="all">
        <method signature="Way2AutomationTest.tc001_addUserAndVerify()[pri:0, instance:org.venkat.test.Way2AutomationTest@1c6804cd]" name="tc001_addUserAndVerify" class="org.venkat.test.Way2AutomationTest"/>
        <method signature="Way2AutomationTest.tc002_addUserAndVerify()[pri:0, instance:org.venkat.test.Way2AutomationTest@1c6804cd]" name="tc002_addUserAndVerify" class="org.venkat.test.Way2AutomationTest"/>
      </group> <!-- all -->
      <group name="ui">
        <method signature="Way2AutomationTest.tc001_addUserAndVerify()[pri:0, instance:org.venkat.test.Way2AutomationTest@1c6804cd]" name="tc001_addUserAndVerify" class="org.venkat.test.Way2AutomationTest"/>
        <method signature="Way2AutomationTest.tc002_addUserAndVerify()[pri:0, instance:org.venkat.test.Way2AutomationTest@1c6804cd]" name="tc002_addUserAndVerify" class="org.venkat.test.Way2AutomationTest"/>
      </group> <!-- ui -->
      <group name="addUser1">
        <method signature="Way2AutomationTest.tc001_addUserAndVerify()[pri:0, instance:org.venkat.test.Way2AutomationTest@1c6804cd]" name="tc001_addUserAndVerify" class="org.venkat.test.Way2AutomationTest"/>
      </group> <!-- addUser1 -->
      <group name="addUser2">
        <method signature="Way2AutomationTest.tc002_addUserAndVerify()[pri:0, instance:org.venkat.test.Way2AutomationTest@1c6804cd]" name="tc002_addUserAndVerify" class="org.venkat.test.Way2AutomationTest"/>
      </group> <!-- addUser2 -->
    </groups>
    <test name="Test_Automation_test" duration-ms="1519" started-at="2018-11-22T02:47:47Z" finished-at="2018-11-22T02:47:48Z">
      <class name="org.venkat.test.Way2AutomationTest">
        <test-method status="FAIL" signature="tc001_addUserAndVerify()[pri:0, instance:org.venkat.test.Way2AutomationTest@1c6804cd]" name="tc001_addUserAndVerify" duration-ms="1104" started-at="2018-11-22T02:47:47Z" finished-at="2018-11-22T02:47:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.venkat.test.Way2AutomationTest.tc001_addUserAndVerify(Way2AutomationTest.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.venkat.api.core.TestExecutor.main(TestExecutor.java:13)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc001_addUserAndVerify -->
        <test-method status="FAIL" signature="tc002_addUserAndVerify()[pri:0, instance:org.venkat.test.Way2AutomationTest@1c6804cd]" name="tc002_addUserAndVerify" duration-ms="370" started-at="2018-11-22T02:47:48Z" finished-at="2018-11-22T02:47:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.venkat.test.Way2AutomationTest.tc002_addUserAndVerify(Way2AutomationTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.venkat.api.core.TestExecutor.main(TestExecutor.java:13)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc002_addUserAndVerify -->
      </class> <!-- org.venkat.test.Way2AutomationTest -->
    </test> <!-- Test_Automation_test -->
  </suite> <!-- Test_Automation_AutomationSuite -->
</testng-results>
